version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: negotiation_chat_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    networks:
      - negotiation-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: negotiation_chat_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - POSTGRES_SERVER=postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always
    networks:
      - negotiation-network

networks:
  negotiation-network:
    driver: bridge

volumes:
  postgres_data: