version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: negotiation_chat_db
    volumes:
      - sqlserver_data:/var/opt/mssql
    env_file:
      - ./.env
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQLSERVER_PASSWORD}
    ports:
      - "1433:1433"
    restart: always
    networks:
      - negotiation-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: negotiation_chat_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - SQLSERVER_SERVER=sqlserver
    ports:
      - "8000:8000"
    depends_on:
      - sqlserver
    restart: always
    networks:
      - negotiation-network

networks:
  negotiation-network:
    driver: bridge

volumes:
  sqlserver_data: